// <auto-generated />
using System;
using HeroRegistry.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HeroRegistry.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251202015642_SeedSuperPoderes")]
    partial class SeedSuperPoderes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HeroRegistry.Domain.Models.Herois.Heroi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("Altura")
                        .HasColumnType("real");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("NomeHeroi")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<float>("Peso")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Herois");
                });

            modelBuilder.Entity("HeroRegistry.Domain.Models.HeroisSuperPoderes.HeroiSuperPoder", b =>
                {
                    b.Property<int>("HeroiId")
                        .HasColumnType("int");

                    b.Property<int>("SuperPoderId")
                        .HasColumnType("int");

                    b.HasKey("HeroiId", "SuperPoderId");

                    b.HasIndex("SuperPoderId");

                    b.ToTable("HeroisSuperpoderes");
                });

            modelBuilder.Entity("HeroRegistry.Domain.Models.SuperPoderes.Poder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("SuperPoder")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("SuperPoderes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Capacidade de exercer força além dos limites humanos.",
                            SuperPoder = "Super Força"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Permite ao herói voar a grandes altitudes e velocidades.",
                            SuperPoder = "Voo"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Movimenta-se em velocidades extremamente altas.",
                            SuperPoder = "Velocidade Sobrenatural"
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "Resistência extrema a danos físicos.",
                            SuperPoder = "Invulnerabilidade"
                        },
                        new
                        {
                            Id = 5,
                            Descricao = "Capacidade de mover objetos com a mente.",
                            SuperPoder = "Telecinese"
                        },
                        new
                        {
                            Id = 6,
                            Descricao = "Fica completamente invisível ao olho humano.",
                            SuperPoder = "Invisibilidade"
                        },
                        new
                        {
                            Id = 7,
                            Descricao = "Consegue se curar rapidamente de ferimentos.",
                            SuperPoder = "Regeneração"
                        },
                        new
                        {
                            Id = 8,
                            Descricao = "Manipula elementos naturais como fogo, água, ar e terra.",
                            SuperPoder = "Controle de Elementos"
                        },
                        new
                        {
                            Id = 9,
                            Descricao = "Permite enxergar através de objetos.",
                            SuperPoder = "Visão de Raios-X"
                        },
                        new
                        {
                            Id = 10,
                            Descricao = "Cria, controla e absorve diversos tipos de energia.",
                            SuperPoder = "Manipulação de Energia"
                        });
                });

            modelBuilder.Entity("HeroRegistry.Domain.Models.HeroisSuperPoderes.HeroiSuperPoder", b =>
                {
                    b.HasOne("HeroRegistry.Domain.Models.Herois.Heroi", "Heroi")
                        .WithMany("SuperPoderes")
                        .HasForeignKey("HeroiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeroRegistry.Domain.Models.SuperPoderes.Poder", "SuperPoder")
                        .WithMany()
                        .HasForeignKey("SuperPoderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Heroi");

                    b.Navigation("SuperPoder");
                });

            modelBuilder.Entity("HeroRegistry.Domain.Models.Herois.Heroi", b =>
                {
                    b.Navigation("SuperPoderes");
                });
#pragma warning restore 612, 618
        }
    }
}
